// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "qjJgHfXn?y8j/R}0:)=8":
            case "helldiver with gun not firing right":return img`
........................fffffffffff..............................
.......................f55555555554f.............................
.......................f55555555554f.............................
.....................ff5ccccccccccc5fc...........................
.....................ff5cccccccccccc54b..........................
.....................ff5cccccccccccc54b..........................
.....................ff5cccddcbbbbbbbbbbb........................
..................fff55cccccccff999996f......fcbbcf..............
..................fff55cccccccff999996f......fcbbcf..............
.................fccfcccccccccff9999fff......ccbbbbbbbbbbbbbb....
...............ffcccfffffffcccccffffbcfffffffffffffffffffffffff..
...............ffcccfffffffcccccffffbcfffffffffffffffffffffffff..
..............fccffffcccbbbfffff5ffbbcfbbbccb4555555555bbccccffff
............ffcff555fffcccccccccfbbbbcffcbbbbbbbbbbbbbbbbbbbbccbf
............ffcff555fffcccccccccfbbbbcffcbbbbbbbbbbbbbbbbbbbbccbf
............fffffffffccfffffffff5ffbbcfffccccccccccccbbbbbbbbcfff
...........ffffffffffcccffcccffffffffffffffccffffffffcccccccccf..
...........ffffffffffcccffcccffffffffffffffffffffffffffffffffff..
..........fc55cccffffccfccbbbcccffffffffffffcccccff..............
..........fccc5cccfffffccccbbcfffcccfc554ccccfffff...............
..........fccc5cccfffffcccccbcfffcccfc554ccccccfff...............
..........fccccccfffffffccccccfffcccfcccccccffff.................
..........ffccccfcccffffffffffffccccfccccccccccf.................
..........ffcccfccccffffffffffffbbbbfcccccccffff.................
............fffcccccfffccccff.fffffffffffffffff..................
..............fcccccfccccccffd...................................
..............fcccccfcccbccffd...................................
...............ccccffcccbccfff...................................
...............ffffffffcccffffff.................................
...............ffffffffcccffffff.................................
...............ffffffffffffffffffff..............................
..............fcccfffffcffffffffccff.............................
..............fcccfffff.ffffffffccff.............................
............ffccccccf...ffffffccc54f.............................
...........fccccc5ccf.....fffcccc54cfc...........................
...........fccccc5ccf.....fffcccc54cfc...........................
.........ffcccc55cccf.....fffcccccccfc...........................
.........ffcccccccccf.....fffcccccccfc...........................
.........ffcccccccccf.....fffcccccccfc...........................
........fcccccccccffc......ffcccccccfc...........................
.....fffffffffccccfff......ffcccccfffff..........................
.....fffffffffccccfff......ffcccccfffff..........................
.....fff5555fffccf.........ffccccffffe5fc........................
...fffffffffffffff........ffffffffffffffff.......................
...fffffffffffffff........ffffffffffffffff.......................
..ffffffffffffffff........fffffffffffffffffb.....................
..ffffffffffffffff........fffffffffffffffffb.....................
..ffffffffffffffff........fffffffffffffffffb.....................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
